### ISSUE TITLE
Allow merge so noiw linear

### ISSUE THREAD

**Issue by stbischof** [eclipse-osgi-technology/.eclipsefdn#3]
https://github.com/eclipse-osgi-technology/.eclipsefdn/blob/9aab9f88bdccae7aaa9dcbbd88540328fba6b66a/otterdog/eclipse-osgi-technology.jsonnet#L5

**Comment by netomi** [comment]
Can you give a bit more context what this issue is all about?

**Comment by stbischof** [comment]
I had a meeting with teams members ans i just madr a comment in the things in have to change. Nothing to donfor you Thomas
